config/routes.rb
Rails.application.routes.draw do
  resources :products

  devise_for :users
  root 'pages#home'
  
  get 'dashboard' => "pages#dashboard"
  
  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       can :read, :all
       can :manage, Product do |product|
         product.try(:user) == user
       end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
        extend FriendlyId
        friendly_id :name, use: :slugged
        
        belongs_to :user
        has_many :sales
        has_attached_file :image
        
        validates_attachment_content_type :image, 
content_type:  /^image\/(png|gif|jpeg)/,
message: "Only images allowed"



validates :image, attachment_presence: true
validates_numericality_of :price,
greater_than: 49, message: "must be atleast 50 cents"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
    before_create :populate_guid
    belongs_to :product
    
    include AASM
    
    aasm column: 'state' do
	state :pending, initial: true
	state :processing
	state :finished
	state :errored
	
	event :process, after: :charge_card do
		transitions from: :pending, to: :processing
	end
	
	event :finish do
		transitions from: :processing, to: :finished
	end
	
	event :fail do 
		transitions from: :processing, to: :errored
	end
end
    def charge_card
        begin
        save!
        charge = Stripe::Charge.create(
            amount: self.amount,
            currency: "cad",
            card: self.stripe_token,
            description: "Product Sale"
            )
        self.update(stripe_id: charge.id)
        self.finish!
    rescue Stripe::StripeError => e
    self.update_attributes(error: e.message)
    self.fail!
    end
    end
    
    
    private 
    
    def populate_guid
        self.guid = SecureRandom.uuid()
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: "You are not authorized to access this area"
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_action :authenticate_user!, only: [:dashboard]
  def home
  	if current_user
redirect_to products_path
  	end
  	@products = Product.last(4)
  end
  
  def dashboard
    @products =current_user.products
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.where(availability: true)
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
    authorize! :manage, @product
  end

  def create
    @product = current_user.products.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    authorize! :manage, @product
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    authorize! :manage, @product
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
     @product = Product.friendly.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :points, :availability, :image)
    end
end

app/controllers/transaction_controller.rb
class TransactionsController < ApplicationController
    def create
    product = Product.find_by!(slug: params[:slug])
    token = params[:stripeToken]
    
    begin 
    charge = Stripe::Charge.create(
        amount: product.price,
        currency: "cad",
        card: token,
        description: current_user.email
        )
        @sale = product.sales.create!(
            buyer_email: current_user.email)
            redirect_to pickup_url(guid: @sale.guid)
            rescue Stripe::CardError => e
            @error = e
            redirect_to product_path(product), notice: @error
    end

    def pickup
        @sale = Sale.find_by!(guid: params[:guid])
        @product = @sale.product
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def create
    product = Product.find_by!(slug: params[:slug])
    token = params[:stripeToken]
    sale = product.sales.create(
        amount: product.price,
        buyer_email: current_user.email,
        seller_email: product.user.email,
        stripe_token: params[:stripeToken])    
        sale.process!
        if sale.finished?
            redirect_to pickup_url(guid: sale.guid), notice: "Transaction Successful"
        else
            redirect_to product_path(product), notice: "Something went wrong"
        end
    end
    def pickup
        @sale = Sale.find_by!(guid: params[:guid])
        @product = @sale.product
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to(image_tag("logo.png", :alt => "logo", :title => "KarmaBuy", :class=>"img-responsive2"), "/") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Shop", products_path %></li>
        
        <% if current_user %>
      
      <li><%= link_to "Settings", edit_user_registration_path %></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
      
      <% else %>
      
        <li><%= link_to "Login", new_user_session_path %></li>
      
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Karmabuy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div Class="container">
  <% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/_books.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Available</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          <% @products.each do |product| %>        
          <tr>
          <th scope="row"><%= product.id %></th>
          <td> <%= link_to product.name, product_path(product) %></td>
          <td><%= product.availability %></td>
          <td><%= link_to "Edit", edit_product_path(product) %></td>
        </tr>
        <% end %>
         
      </tbody>
    </table>

app/views/pages/_purchased.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
         </tr>
      </thead>
      <tbody>
          <% @purchased.each do |sale| %>        
          <tr>
          <td> <%= link_to sale.product.name, pickup_path(sale.guid) %></td>
          <td><%= time_ago_in_words(sale.created_at) %> ago</td>
          
        </tr>
        <% end %>
         
      </tbody>
    </table>

app/views/pages/_sales.html.erb
<table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Buyer</th>
         </tr>
      </thead>
      <tbody>
          <% @sales.each do |sale| %>        
          <tr>
          <td> <%= link_to sale.product.name, pickup_path(sale.guid) %></td>
          <td><%= time_ago_in_words(sale.created_at) %> ago</td>
          <td><%= sale.buyer_email %></td>
          
        </tr>
        <% end %>
         
      </tbody>
    </table>

app/views/pages/dashboard.html.erb
<div class="row">
    <h1 class="text-center">Dashboard</h1>
<div class="col-md-4">
    <h3 class="text-center">Products
    <%= link_to "New Product" , new_product_path, class: "btn btn-primary btn-sm" %>
    </h3>
    <%= render "books" %>
    </div> 
    <div class="col-md-4">
    <h3 class="text-center">Purchases</h3>
    <%= render "purchased" %>
    </div>    
    <div class="col-md-4">
    <h3 class="text-center">Sales</h3>
    <%= render "sales" %>
    </div>    
    
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to KarmaBuy!</h1>
  <p>Buying Never Felt So Good</p>
  <%= link_to "Browse Products", products_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  
</div>
<div class="row">
  <%= render @products %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, required: true, label: false, placeholder: "Product Name", input_html: {class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Description", input_html: {class: "form-control", rows: 5}
    %>
    <%= f.input :price, required: true, label: false, placeholder: "Price", input_html: {class: "form-control"}  %>
    <%= f.input :points, required: true, label: false, placeholder: "Karma Points", input_html: {class: "form-control"}  %>
    <%= f.input :image %>
   
    <div class="checkbox text-center">
    <p>Published?</p>
    <%= f.input :availability, required: false, label: false  %>
 </div>


    <%= f.button :submit, class: "btn btn-primary btn-block" %>

<% end %>

app/views/products/_product.html.erb
<div class="col-md-3">
    <div class="thumbnail">
        <%= link_to product_path(product) do %>
      <%= image_tag product.image.url(:original), class: "img-responsive" %>
      <% end %>
      <div class="caption">
        <p><strong><%= link_to product.name, product_path(product)  %></strong></p>
        <p>$<%= product.price.to_f / 100 %></p>
        <p><%= product.points %>KP</p>
      </div>
    </div>
  </div>
  

app/views/products/edit.html.erb
<h1 class="text-center">Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row">
  <%= render @products %>
</div>

app/views/products/new.html.erb
<h1 class="text-center">New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
<div class="col-md-6">
  <%= image_tag @product.image.url(:original), class: "img-responsive" %>
  </div>
  <div class="col-md-6">
    <h3> <%= @product.name %></h3>
    <p><%= @product.description %></p>
    <h4 class="text-center">$ <%= @product.price.to_f / 100 %></h4>
    
    <%= form_tag buy_path(slug: @product.slug) do %>
    <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-amount="<%= @product.price %>"
    data-name="KarmaBuy"
    data-description="<%= @product.name %>"
    data-image="<%= image_tag("logo.png")%>"
    data-email="<%= current_user.email %>"
    data-shipping-address="true"
    data-billing-address="false"
    data-locale="auto">
  </script>
    <% end %>
    
</div>
</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
    <h1>Congratulations on your order <%= @sale.guid %></h1>
    
</div>